ekf_filter_node:
  ros__parameters:
    frequency: 20.0
    two_d_mode: true
    publish_tf: true
    print_diagnostics: true
    sensor_timeout: 0.2

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ---------- Wheel odometry ----------
    odom0: /odom
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false

    # x, y, yaw, vx, wz
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  false, false,
                   false, false, true,
                   false, false, false]

    # ---------- IMU ----------
    imu0: /imu/data_raw
    imu0_queue_size: 50
    imu0_nodelay: true
    imu0_differential: false
    imu0_relative: true
    imu0_qos: sensor_data

    # yaw and yaw rate only
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    imu0_remove_gravitational_acceleration: false
