controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/joint_state_broadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

simple_velocity_controller:
  ros__parameters:
    joints:
      - right_rear_wheel_joint
      - right_mid_wheel_joint
      - right_front_wheel_joint
      - left_rear_wheel_joint
      - left_mid_wheel_joint
      - left_front_wheel_joint
      
