controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    use_stamped_vel: false
    left_wheel_names:
      - left_front_wheel_joint
      - left_mid_wheel_joint
      - left_rear_wheel_joint
    right_wheel_names:
      - right_front_wheel_joint
      - right_mid_wheel_joint
      - right_rear_wheel_joint

    wheel_radius: 0.05
    wheel_separation: 0.509

    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false
    cmd_vel_timeout: 0.5    